# Mandatory property for FhirAutoConfiguration (unless you wish to use the default DSTU2 model and already have it on
# the classpath.) Note that you cannot create the R4 context programatically (i.e. setFhirContext(FhirContext.forR4());)
# since this occurs after FhirAutoConfiguration is run.
hapi:
  fhir:
    version: R4
spring:
  sql:
    init:
      mode: embedded
  datasource:
    url: jdbc:h2:file:./training_fhir
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
server:
  servlet:
    context-path: /fhir
application:
  sql:
    enabled: false # if not h2, set enabled: true
jwt:
  secret: PAijPEaeHbCakqBDwxdFJcpffqOknRS3
  token:
    validity: 3600000