# Mandatory property for FhirAutoConfiguration (unless you wish to use the default DSTU2 model and already have it on
# the classpath.) Note that you cannot create the R4 context programatically (i.e. setFhirContext(FhirContext.forR4());)
# since this occurs after FhirAutoConfiguration is run.
hapi:
  fhir:
    version: R4
spring:
  sql:
    init:
      mode: embedded
  datasource:
    url: jdbc:h2:file:./training_fhir
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/Fhir
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
server:
  port: 8081
  servlet:
    context-path: /fhir
application:
  sql:
    enabled: false # if not h2, set enabled: true
  token:
    converter:
      resource-id: fhir-api
      url: http://localhost:8181/v1/data
logging:
  level:
    root: INFO
    owt.training.fhir: DEBUG
    org.springframework.security.web: DEBUG