server:
  port: 8081
  servlet:
    context-path: /domain-resource-service
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/Fhir
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

application:
  token:
    converter:
      resource-id: fhir-api