management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus
server:
  port: 8081
  servlet:
    context-path: /domain-resource-service
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_local?currentSchema=schema1
    user: root
    password: 123456
    driverClassName: org.postgresql.Driver
  liquibase:
    url: jdbc:postgresql://localhost:5432/test_local?currentSchema=schema1
    user: root
    password: 123456
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/Fhir
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: full
application:
  token:
    converter:
      resource-id: fhir-api
  opa:
    authz:
      url: http://localhost:8181/v1/data
logging:
  level:
    root: INFO
    owt.training.fhir: DEBUG
    org.springframework.security.web: DEBUG